name: Deploy
on:
  push:
    branches: [
      master
    ]

jobs:
  build:
    name: SSH, compile and deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Setup repo
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Install dependencies
      run: yarn install --frozen-lockfile --production=true

    - name: Build
      run: yarn build

    - name: "Rsync target folder to remote"
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: '-p 22'
        src: ./build/
        dest: ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/labelmaker.${{ secrets.USER }}.com/
          
