name: Deploy
on:
  push:
    branches: [
      master
    ]

jobs:
  build:
    name: Install, build and rsync
    runs-on: ubuntu-20.04

    steps:
    - name: Setup repo
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --production=true

    - name: Build
      run: yarn build

    - name: "Rsync build folder to remote"
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.KEY }}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: '-p 22'
        src: ./build/
        dest: ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/labelmaker.borozky.com/
          
